
  export const DataPro = [
         {
            columns: [{
                id: '1',
                name:'В очереди',
                color: 'red',
                status: 'to_do',
                taskIds: ['1002', '1001'],
            },{
                id: '2',
                name:'В работе',
                color: 'blue',
                status: 'in_progress',
                taskIds: ['1003'],
            },{
                id: '3',
                name:'Требуется проверка',
                color: 'yellow',
                status: 'need_review',
                taskIds: ['1004'],
            },{
                id: '4',
                name:'Выполнено',
                color: 'green',
                status: 'done',
                taskIds:['1005', '1006'],
            },],
          nameProject: "Project#1",
          cards:[{
                id: '1001',
                Label: "Label#1",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                members: "alice",
                comments: "4",
                views: "6",
                files: "0",
                tag: "testTag",
                date: "create date",
                status: "to_do",
                id_column:'1',
            },
            {
                id: '1002',
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                Label: "Label#2",
                members: "john",
                comments: "1",
                views: "8",
                files: "1",
                tag: "testTag",
                date: "create date",
                status: "to_do",
                id_column:'1',
            },
            {
                id: '1003',
                Label: "Label#3",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                members: "cedric",
                comments: "2",
                views: "10",
                files: "3",
                tag: "testTag",
                date: "create date",
                status: "in_progress",
                id_column:'2',
            },
            {
                id: '1004',
                Label: "Label#4",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                members: "mila",
                comments: "1",
                views: "7",
                files: "0",
                tag: "testTag",
                date: "create date",
                status: "need_review",
                id_column:'3',
            },
            {
                id: '1005',
                Label: "Label#5",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                members: "kir",
                comments: "9",
                views: "15",
                files: "5",
                tag: "testTag",
                date: "create date",
                status: "done",
                id_column:'4',
            },
            {
                id: '1006',
                Label: "Label#6",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                members: "riga",
                comments: "4",
                views: "87",
                files: "9",
                tag: "testTag",
                date: "create date",
                status: "done",
                id_column:'4',
            },
            
          ],}
    ];




